### ISSUE TITLE
List of Issues

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#36]
#Incomplete list of significant changes to content that needs to be written and/or revised:

**General**
- [x] See the standard [lesson release checklist #47 ](https://github.com/datacarpentry/shell-genomics/issues/47) for things to look for when creating issues.
- [x] #1 Deletion of master branch - both files in master branch are present in gh-pages so master branch could be deleted
- [x] Write [instructor notes](https://github.com/datacarpentry/shell-genomics/issues/13)
- [x] Add [Setup instructions](http://www.datacarpentry.org/shell-genomics/setup/) either for shell specifically, or for the entire genomics lesson? This is an [open question](https://github.com/datacarpentry/organization-genomics/issues/30).
- [x] [Extras -> References, About, Discussion, and Figures need content as noted in #38 ](https://github.com/datacarpentry/shell-genomics/issues/38)
- [ ] Find a single place to list resources for further learning. At present, they appear at the ends of both  [episode 1](http://www.datacarpentry.org/shell-genomics/01-introduction/) and [episode 5](http://www.datacarpentry.org/shell-genomics/05-writing-scripts/). See this additional [resource](https://github.com/datacarpentry/shell-genomics/issues/29), which also needs a home.
- [x] [slides.md](https://github.com/datacarpentry/shell-genomics/blob/gh-pages/slides.md) is mentioned in some issues and PRs. Is it deprecated? It doesn't seem to be part of this lesson any longer. See [PR 9](https://github.com/datacarpentry/shell-genomics/pull/9) and [issue 23](https://github.com/datacarpentry/shell-genomics/issues/23).

**Episode 1- Introducing the Shell**
- [x] [Typos noted in #39 ](https://github.com/datacarpentry/shell-genomics/issues/39)

**Episode 2 - The Filesystem**
- [x] [Time estimates, key points, and more needed as noted in #38](https://github.com/datacarpentry/shell-genomics/issues/38)
- [x] [provide starting working directory for exercise: finding hidden files as noted in #40](https://github.com/datacarpentry/shell-genomics/issues/40)

**Episode 3 - Working with Files**
- [x] [Exercise: List all of the files in /usr/bin](https://github.com/datacarpentry/shell-genomics/issues/10)
- [x] [Time estimates, key points, and more needed as noted in #38](https://github.com/datacarpentry/shell-genomics/issues/38)
- [x] [Confusing wording `the home directory` as noted in #41](https://github.com/datacarpentry/shell-genomics/issues/41)

**Episode 4 - Redirection**
- [x] Add this [exercise](https://github.com/datacarpentry/shell-genomics/issues/35) to search man pages.
- [x] [Time estimates, key points, questions, and solutions needed as noted in #38](https://github.com/datacarpentry/shell-genomics/issues/38)
- [x] [Formatting issues in Redirection & Writing Scripts episodes as noted in #42 ](https://github.com/datacarpentry/shell-genomics/issues/42)
- [x] [Typos noted in #43 ](https://github.com/datacarpentry/shell-genomics/issues/43)
- [x] [sequence counting with `wc -l `  as noted in #46 ](https://github.com/datacarpentry/shell-genomics/issues/46)

**Episode 5 - Writing Scripts**
- [x] Clean up links [at bottom of page](http://www.datacarpentry.org/shell-genomics/05-writing-scripts/) or move all learning resources to a single place. There are currently others listed at the end of episode 1 as well.
- [x] [Time estimates and more needed as noted in #38](https://github.com/datacarpentry/shell-genomics/issues/38)
- [x] [Permissions discussion incomplete as noted in #45](https://github.com/datacarpentry/shell-genomics/issues/45)
- [x] Nano screen-shot shows a different file name on the titlebar (shows awesome.sh, should be README.txt)

**Episode 6 - Project Organization**
- [x] [Time estimates, key points, questions, objectives and more needed as noted in #38](https://github.com/datacarpentry/shell-genomics/issues/38)
- [x] [Episode 6 appears somewhat out of order and "Questions" is more suitable for episode `Redirection` as noted in #44](https://github.com/datacarpentry/shell-genomics/issues/44)

**Comment by mfoos** [comment]
The link to SWC at the bottom of Writing Scripts is also broken

**Comment by psorianom** [comment]
Hey! I am doing my instructor checkout.  I would add to this list, in episode 5: 
- [ ] Nano screen-shot shows a different file name on the titlebar (shows _awesome.sh_, should be _README.txt_)

**Comment by aschuerch** [comment]
Thank you @psorianom! Added.

**Comment by ErinBecker** [comment]
Moved two remaining issues to separate issues. Closing here.
