### ISSUE TITLE
Standard Lesson Release Checklist

### ISSUE THREAD

**Issue by smcclatchy** [datacarpentry/shell-genomics#47]
## Lesson Release checklist

**For each lesson release, copy this checklist to an issue and check off
during preparation for release**

Scheduled Freeze Date:   YYYY-MM-DD  
Scheduled Release Date:  YYYY-MM-DD  

Checklist of tasks to complete before release:

- [ ] check that the learning objectives reflect the content of the lessons
- [ ] check that learning objectives are phrased as statements using action words
- [ ] check for typos
- [ ] check that the live coding examples work as expected
- [ ] if example code generates warnings, explain in narrative and instructor notes
- [ ] check that challenges and their solutions work as expected
- [ ] check that the challenges test skills that have been seen
- [ ] check that the setup instructions are up to date (e.g., update version numbers)
- [ ] check that data is available and mentions of the data in the lessons are accurate
- [ ] check that the instructor guide is up to date with the content of the lessons
- [ ] check that all the links within the lessons work (this should be automated)
- [ ] check that the cheat sheets included in lessons are up to date (e.g., RStudio updates them regularly)
- [ ] check that languge is clear and free of idioms and colloquialisms
- [ ] make sure formatting of the code in the lesson looks good (e.g. line breaks)
- [ ] check for clarity and flow of narrative
- [ ] update README as needed
- [ ] fill out “overview” for each module - minutes needed for teaching and exercises, questions and learning objectives
- [ ] check that contributor guidelines are clear and consistent
- [ ] clean up files (e.g. delete deprecated files, insure filenames are consistent)
- [ ] update the release notes (NEWS)
- [ ] tag release on GitHub

**Comment by mkuzak** [comment]
Thanks @smcclatchy this is great, I would add:
- [ ] update maintainers list
- [ ] update contributors list (check with the contributors if they want to be mentioned as the coauthors of the release )
- [ ] cleanup white space (no mixing spaces and tabs, remove trailing space)

**Comment by ErinBecker** [comment]
The contributors list (AUTHORS.md) will be automatically updated during the lesson release process.
