### ISSUE TITLE
Issue list 02-the filesystem

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#91]
Main page (http://www.datacarpentry.org/shell-genomics/)
- [x] missing key questions on main page

Episode page (http://www.datacarpentry.org/shell-genomics/02-the-filesystem/)
- [x] missing time estimate for teaching, also mentioned in #38
- [x] missing time estimate for exercises, also mentioned in #38
- [x] missing key questions, also mentioned in  #38 
- [x] Objective "Keyboard shortcuts to make work more efficiently at the command line" should be re-phrased
- [x] Introductory sentences: "As you’ve already just seen, you can move around in different directories or folders at the command line. Why would you want to do this, rather than just navigating around by clicking on folders as you might usually do." should be re-phrased (sounds slightly dismissive to me)

- [x] Hidden exercise:  Provide starting directory, as mentioned in #40 

- [x] "To summarize, while you are in the shell directory.." is confusing, needs to be re-phrased. See also #59 
- [x] key points missing, also mentioned in #38

**Comment by ErinBecker** [comment]
@aschuerch I added "-" in front of each "[ ]" so the checkboxes would render. Thanks for putting this together!

**Comment by ErinBecker** [comment]
Working on this list now!
